### ISSUE TITLE
How can i add ngx-dynamic-dashboard-framework on existing project 

### ISSUE THREAD

**Issue by Sofiane-13** [catalogicsoftware/ngx-dynamic-dashboard-framework#10]
Hello,
I am searching a way to add this framework on my existing angular 4 project, so if someone have a good tutorial or advice it can be amazing.
Thank you !

**Comment by jayhamilton** [comment]
@Sofiane-13 this started as an Angular 4 project. You can try to go back in the git history to an older git commit from about a year ago when it was leveraging Angular 4 and checkout the code. The core framework did not dramatically change since then.
