### ISSUE TITLE
Upgrade to Angular 6

### ISSUE THREAD

**Issue by DavidDury** [catalogicsoftware/ngx-dynamic-dashboard-framework#11]
Hi guys, do you have any plans to upgrade this to Angular 6? Just tried it and got quite few errors and I am stuck. Thanks in advance!

**Comment by jayhamilton** [comment]
I will probably spend time on this next week.

**Comment by jayhamilton** [comment]
Hope to have this updated to Angular 6 by the end of the week. I overcome most of the migration issues. A few more remain that should be straightforward to resolve.

**Comment by DavidDury** [comment]
@jayhamilton : Great! Much appreciated! Awesome work guys!

**Comment by jayhamilton** [comment]
Upgrade to Angular 6 has been completed.

**Comment by DavidDury** [comment]
@jayhamilton : Thank you!
