### ISSUE TITLE
Minimize the use of session/local storage while creating board

### ISSUE THREAD

**Issue by 9561690684** [catalogicsoftware/ngx-dynamic-dashboard-framework#18]
In this project we are using local and session storage to get render the boards/widget etc. Is there any way to transfer control to developer?

**Comment by jayhamilton** [comment]
feeding in the board's data structure programmatically as input is definitely doable. At some point I actually wrote the code to do that. All you need to do is create an @input property on the GridComponent and associate it with the model class variable. The value of the Input property can be derived from app/services/configuration-sample-boards.model.ts You can pass it in via the BoardComponent's view.html.

**Comment by 9561690684** [comment]
@jayhamilton - Thanks for your inputs.
I don't want to change in existing code so is there any other way to do this. something like extending the existing components and then write all code over there. Please let me know if you have any other different way.
