### ISSUE TITLE
Do we have any documentation for this framework?

### ISSUE THREAD

**Issue by 9561690684** [catalogicsoftware/ngx-dynamic-dashboard-framework#19]
Do we have any documentation for this framework. Please provide if anyone have. It will help beginner to study this framework easily.

**Comment by jayhamilton** [comment]
The framework includes documentation under the following location:
https://github.com/catalogicsoftware/ngx-dynamic-dashboard-framework/tree/master/src/assets/documentation
This is generated documentation using a framework called compdoc. The documentation available maybe a bit out of date, however, it can be generated by installing the compdoc npm package and then running the command to generate it.  See the following youtube video:
https://www.youtube.com/watch?v=7pJ9lsu6jDw

It is HTML documentation, so if you go to the location above and then launch the index.html page the documentation will appear in the browser.

**Comment by 9561690684** [comment]
Thanks jay providing this information but i have already gone through above location but i am looking out for more documentation. If you have any tutorial for this please let me know.

Is there any YouTube tutorials available for this framework?

**Comment by 9561690684** [comment]
As I am totally new to angular and ngx-dynamic-dashboard framework and learning form scratch everything, so please help me to clarify few doubts. Thanks in advance for your valuable support and time. 

Is this project or library? As per my knowledge this is project under development. But If this is library then what is the current version going on? Please provide any tutorials (YouTube link or anything) link if exists.

**Comment by jayhamilton** [comment]
Nitin,
This is a project that had the intent to becoming a library but this has not materialized. I would recommend forking the code and experimenting with various approaches to accomplish your goal. I will do what I can to help.
