### ISSUE TITLE
Not able to generate any new component

### ISSUE THREAD

**Issue by ashutosh15aashu** [catalogicsoftware/ngx-dynamic-dashboard-framework#21]
Hey,

I was trying to create sample new component after installing npm and successful executing the app but, not able to create new component. 

I was getting one message:
  "Two or more projects are using identical roots. Unable to determine project using current working directory. Using default work space project instead. More than one module matches. Use skip-import option to skip importing the component into the closest module." 

Please help me on this:
  -how to create new components?
  -try to attach any documentation(How to modify the application) link, if it is there. 

Thanks-
Ashutosh kumar.

**Comment by jayhamilton** [comment]
It may be an issue with the version of Angular CLI you are using. See if the following is relevant?
https://github.com/angular/angular-cli/issues/11688

**Comment by ashutosh15aashu** [comment]
@jayhamilton 
Already, i checked Angular cli version things but, it is not occurring due to version issue.
You are using almost separate module for all component.
When i'm trying to generate the component it is not able to get the module path or something related to that.
I am using the command( ng generate component sample_component ) to generate the sample component.
Please, check the screenshots attached below and give any better suggestion.
Thanks-
 
![image](https://user-images.githubusercontent.com/20661597/56639777-14fd1e80-668f-11e9-9c9c-5ef718c28b0e.png)

**Comment by ashutosh15aashu** [comment]
I got and fixed that.
I have to pass module name with commands.

>ng g component sample_component --module=app.module

-Thanks.
