### ISSUE TITLE
How can i add d3.js charts in the gadget?

### ISSUE THREAD

**Issue by ashutosh15aashu** [catalogicsoftware/ngx-dynamic-dashboard-framework#23]
How to add d3.js charts with given gadget in this framework instead of ngx-chart.

Please, share any link or explain the steps.

**Comment by jayhamilton** [comment]
Don't have a link but may have an example. You could also look at the source for NGX Charts which is based on D3.

**Comment by jayhamilton** [comment]
Follow the instructions in this project's readme for adding a new gadget and then review the following article. This article is pretty straightforward: https://medium.com/@jeanphilippelemieux/creating-a-responsive-graph-with-angular-and-d3-b45bb8065588
D3 is already part of this project so there will be no need to install it. Try it out and if you get it working contribute it back to this project.
