### ISSUE TITLE
where is the 'view' variable comes from 

### ISSUE THREAD

**Issue by MHL3060** [catalogicsoftware/ngx-dynamic-dashboard-framework#28]
Hi, Thanks for creating a such good dashboard.

I am evaluating the dashboard framework and try to understand how thing works, 

I am trying to integrate this dashboard into jhipster which is using Angular 10, but it is complainting the `view` variable is undefined during compilation.

can you please tell me where the 'view' comes from in this snippet. the one on the right hand side. Thanks.

in src/app/gadgets/disk/view.html
I couldn't find the this variable in the disk-gadget.component.ts or its super class.
```
<ngx-charts-pie-chart *ngIf="!inConfig"
                        [view]="view"
                        [scheme]="colorScheme"
                        [results]="data"
                        [legend]="true"
                        [explodeSlices]="false"
                        [labels]="false"
                        [doughnut]="true"
                        [gradient]="false"
                        [arcWidth]=".4"
                        (select)="drillDownPopUp.showDetail($event)">
                </ngx-charts-pie-chart>
```

**Comment by jayhamilton** [comment]
view is a property of ngx-charts. This is typically set in the components ts file. See https://swimlane.gitbook.io/ngx-charts/examples/bar-charts/normalized-horizontal-bar-chart.

**Comment by MHL3060** [comment]
thanks. I see. some of the variables in the template doesn't exists in the component. that is why I was wondering.
