### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by itopix** [catalogicsoftware/ngx-dynamic-dashboard-framework#3]
Hi,

I like your framework. I have some questions. Can you send me your email?

Jordy

**Comment by jayhamilton** [comment]
Jordy has some questions regarding roadmap items for the framework. Here are some todos:
- improve error handling
- add tests
- develop the notification component more
- provide a more generic set of gadgets/charts. The gadgets I created were specific to metric collection. I would like to have a few generic gadgets that allow you to pick the chart type and end point provided the endpoint returns the proper data format. 
- allow the user to select between simulated mode for using mock data vs live data mode.
- more work on drill down
- email notification
- data/chart export
